//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("", ClrNamespace="")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://FileLocalSCS/", ClrNamespace="filelocalscs")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://FileLocalSCS/Faults/", ClrNamespace="filelocalscs.Faults")]



[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="SCSSoapAuthenticationHeader", Namespace="")]
public partial class SCSSoapAuthenticationHeader : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string AccessKeyField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string AccessKey
    {
        get
        {
            return this.AccessKeyField;
        }
        set
        {
            this.AccessKeyField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://FileLocalSCS/", ConfigurationName="ISCS")]
public interface ISCS
{
    
    // CODEGEN: Generating message contract since message PrintGBLRequest has headers
    [System.ServiceModel.OperationContractAttribute(Action="http://FileLocalSCS/ISCS/PrintGBL", ReplyAction="http://FileLocalSCS/ISCS/PrintGBLResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(filelocalscs.Faults.StandardFault), Action="http://FileLocalSCS/ISCS/PrintGBLStandardFaultFault", Name="StandardFault", Namespace="http://FileLocalSCS/Faults/")]
    PrintGBLResponse PrintGBL(PrintGBLRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://FileLocalSCS/ISCS/PrintGBL", ReplyAction="http://FileLocalSCS/ISCS/PrintGBLResponse")]
    System.Threading.Tasks.Task<PrintGBLResponse> PrintGBLAsync(PrintGBLRequest request);
    
    // CODEGEN: Generating message contract since message CalculateGBLRenewalRequest has headers
    [System.ServiceModel.OperationContractAttribute(Action="http://FileLocalSCS/ISCS/CalculateGBLRenewal", ReplyAction="http://FileLocalSCS/ISCS/CalculateGBLRenewalResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(filelocalscs.Faults.StandardFault), Action="http://FileLocalSCS/ISCS/CalculateGBLRenewalStandardFaultFault", Name="StandardFault", Namespace="http://FileLocalSCS/Faults/")]
    [System.ServiceModel.FaultContractAttribute(typeof(filelocalscs.Faults.XmlSchemaValidationFault), Action="http://FileLocalSCS/ISCS/CalculateGBLRenewalXmlSchemaValidationFaultFault", Name="XmlSchemaValidationFault", Namespace="http://FileLocalSCS/Faults/")]
    CalculateGBLRenewalResponse CalculateGBLRenewal(CalculateGBLRenewalRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://FileLocalSCS/ISCS/CalculateGBLRenewal", ReplyAction="http://FileLocalSCS/ISCS/CalculateGBLRenewalResponse")]
    System.Threading.Tasks.Task<CalculateGBLRenewalResponse> CalculateGBLRenewalAsync(CalculateGBLRenewalRequest request);
    
    // CODEGEN: Generating message contract since message PaymentRejectionReportRequest has headers
    [System.ServiceModel.OperationContractAttribute(Action="http://FileLocalSCS/ISCS/PaymentRejectionReport", ReplyAction="http://FileLocalSCS/ISCS/PaymentRejectionReportResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(filelocalscs.Faults.XmlSchemaValidationFault), Action="http://FileLocalSCS/ISCS/PaymentRejectionReportXmlSchemaValidationFaultFault", Name="XmlSchemaValidationFault", Namespace="http://FileLocalSCS/Faults/")]
    [System.ServiceModel.FaultContractAttribute(typeof(filelocalscs.Faults.StandardFault), Action="http://FileLocalSCS/ISCS/PaymentRejectionReportStandardFaultFault", Name="StandardFault", Namespace="http://FileLocalSCS/Faults/")]
    PaymentRejectionReportResponse PaymentRejectionReport(PaymentRejectionReportRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://FileLocalSCS/ISCS/PaymentRejectionReport", ReplyAction="http://FileLocalSCS/ISCS/PaymentRejectionReportResponse")]
    System.Threading.Tasks.Task<PaymentRejectionReportResponse> PaymentRejectionReportAsync(PaymentRejectionReportRequest request);
    
    // CODEGEN: Generating message contract since message GetStatementRequest has headers
    [System.ServiceModel.OperationContractAttribute(Action="http://FileLocalSCS/ISCS/GetStatement", ReplyAction="http://FileLocalSCS/ISCS/GetStatementResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(filelocalscs.Faults.StandardFault), Action="http://FileLocalSCS/ISCS/GetStatementStandardFaultFault", Name="StandardFault", Namespace="http://FileLocalSCS/Faults/")]
    GetStatementResponse GetStatement(GetStatementRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://FileLocalSCS/ISCS/GetStatement", ReplyAction="http://FileLocalSCS/ISCS/GetStatementResponse")]
    System.Threading.Tasks.Task<GetStatementResponse> GetStatementAsync(GetStatementRequest request);
    
    // CODEGEN: Generating message contract since message ValidateGBLRequest has headers
    [System.ServiceModel.OperationContractAttribute(Action="http://FileLocalSCS/ISCS/ValidateGBL", ReplyAction="http://FileLocalSCS/ISCS/ValidateGBLResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(filelocalscs.Faults.XmlSchemaValidationFault), Action="http://FileLocalSCS/ISCS/ValidateGBLXmlSchemaValidationFaultFault", Name="XmlSchemaValidationFault", Namespace="http://FileLocalSCS/Faults/")]
    [System.ServiceModel.FaultContractAttribute(typeof(filelocalscs.Faults.StandardFault), Action="http://FileLocalSCS/ISCS/ValidateGBLStandardFaultFault", Name="StandardFault", Namespace="http://FileLocalSCS/Faults/")]
    ValidateGBLResponse ValidateGBL(ValidateGBLRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://FileLocalSCS/ISCS/ValidateGBL", ReplyAction="http://FileLocalSCS/ISCS/ValidateGBLResponse")]
    System.Threading.Tasks.Task<ValidateGBLResponse> ValidateGBLAsync(ValidateGBLRequest request);
    
    // CODEGEN: Generating message contract since message ValidateTaxpayerFormRequest has headers
    [System.ServiceModel.OperationContractAttribute(Action="http://FileLocalSCS/ISCS/ValidateTaxpayerForm", ReplyAction="http://FileLocalSCS/ISCS/ValidateTaxpayerFormResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(filelocalscs.Faults.XmlSchemaValidationFault), Action="http://FileLocalSCS/ISCS/ValidateTaxpayerFormXmlSchemaValidationFaultFault", Name="XmlSchemaValidationFault", Namespace="http://FileLocalSCS/Faults/")]
    [System.ServiceModel.FaultContractAttribute(typeof(filelocalscs.Faults.StandardFault), Action="http://FileLocalSCS/ISCS/ValidateTaxpayerFormStandardFaultFault", Name="StandardFault", Namespace="http://FileLocalSCS/Faults/")]
    ValidateTaxpayerFormResponse ValidateTaxpayerForm(ValidateTaxpayerFormRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://FileLocalSCS/ISCS/ValidateTaxpayerForm", ReplyAction="http://FileLocalSCS/ISCS/ValidateTaxpayerFormResponse")]
    System.Threading.Tasks.Task<ValidateTaxpayerFormResponse> ValidateTaxpayerFormAsync(ValidateTaxpayerFormRequest request);
    
    // CODEGEN: Generating message contract since message ValidateTaxpayerAccount2Request has headers
    [System.ServiceModel.OperationContractAttribute(Action="http://FileLocalSCS/ISCS/ValidateTaxpayerAccount2", ReplyAction="http://FileLocalSCS/ISCS/ValidateTaxpayerAccount2Response")]
    [System.ServiceModel.FaultContractAttribute(typeof(filelocalscs.Faults.XmlSchemaValidationFault), Action="http://FileLocalSCS/ISCS/ValidateTaxpayerAccount2XmlSchemaValidationFaultFault", Name="XmlSchemaValidationFault", Namespace="http://FileLocalSCS/Faults/")]
    [System.ServiceModel.FaultContractAttribute(typeof(filelocalscs.Faults.StandardFault), Action="http://FileLocalSCS/ISCS/ValidateTaxpayerAccount2StandardFaultFault", Name="StandardFault", Namespace="http://FileLocalSCS/Faults/")]
    ValidateTaxpayerAccount2Response ValidateTaxpayerAccount2(ValidateTaxpayerAccount2Request request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://FileLocalSCS/ISCS/ValidateTaxpayerAccount2", ReplyAction="http://FileLocalSCS/ISCS/ValidateTaxpayerAccount2Response")]
    System.Threading.Tasks.Task<ValidateTaxpayerAccount2Response> ValidateTaxpayerAccount2Async(ValidateTaxpayerAccount2Request request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="PrintGBL", WrapperNamespace="http://FileLocalSCS/", IsWrapped=true)]
public partial class PrintGBLRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
    public SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="PrintGBLRequest", Namespace="http://FileLocalSCS/", Order=0)]
    public filelocalscs.PrintGBLRequestDetail PrintGBLRequest1;
    
    public PrintGBLRequest()
    {
    }
    
    public PrintGBLRequest(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.PrintGBLRequestDetail PrintGBLRequest1)
    {
        this.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        this.PrintGBLRequest1 = PrintGBLRequest1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="PrintGBLResponse", WrapperNamespace="http://FileLocalSCS/", IsWrapped=true)]
public partial class PrintGBLResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://FileLocalSCS/", Order=0)]
    public filelocalscs.PrintGBLResponseDetail PrintGBLResult;
    
    public PrintGBLResponse()
    {
    }
    
    public PrintGBLResponse(filelocalscs.PrintGBLResponseDetail PrintGBLResult)
    {
        this.PrintGBLResult = PrintGBLResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CalculateGBLRenewal", WrapperNamespace="http://FileLocalSCS/", IsWrapped=true)]
public partial class CalculateGBLRenewalRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
    public SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateGBLRenewalRequest", Namespace="http://FileLocalSCS/", Order=0)]
    public filelocalscs.CalculateGBLRenewalRequestDetail CalculateGBLRenewalRequest1;
    
    public CalculateGBLRenewalRequest()
    {
    }
    
    public CalculateGBLRenewalRequest(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.CalculateGBLRenewalRequestDetail CalculateGBLRenewalRequest1)
    {
        this.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        this.CalculateGBLRenewalRequest1 = CalculateGBLRenewalRequest1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CalculateGBLRenewalResponse", WrapperNamespace="http://FileLocalSCS/", IsWrapped=true)]
public partial class CalculateGBLRenewalResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://FileLocalSCS/", Order=0)]
    public filelocalscs.CalculateGBLRenewalResponseDetail CalculateGBLRenewalResult;
    
    public CalculateGBLRenewalResponse()
    {
    }
    
    public CalculateGBLRenewalResponse(filelocalscs.CalculateGBLRenewalResponseDetail CalculateGBLRenewalResult)
    {
        this.CalculateGBLRenewalResult = CalculateGBLRenewalResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="PaymentRejectionReport", WrapperNamespace="http://FileLocalSCS/", IsWrapped=true)]
public partial class PaymentRejectionReportRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
    public SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentRejectionReportRequest", Namespace="http://FileLocalSCS/", Order=0)]
    public filelocalscs.PaymentRejectionReportRequestDetail PaymentRejectionReportRequest1;
    
    public PaymentRejectionReportRequest()
    {
    }
    
    public PaymentRejectionReportRequest(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.PaymentRejectionReportRequestDetail PaymentRejectionReportRequest1)
    {
        this.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        this.PaymentRejectionReportRequest1 = PaymentRejectionReportRequest1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="PaymentRejectionReportResponse", WrapperNamespace="http://FileLocalSCS/", IsWrapped=true)]
public partial class PaymentRejectionReportResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://FileLocalSCS/", Order=0)]
    public filelocalscs.PaymentRejectionReportResponseDetail PaymentRejectionReportResult;
    
    public PaymentRejectionReportResponse()
    {
    }
    
    public PaymentRejectionReportResponse(filelocalscs.PaymentRejectionReportResponseDetail PaymentRejectionReportResult)
    {
        this.PaymentRejectionReportResult = PaymentRejectionReportResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetStatement", WrapperNamespace="http://FileLocalSCS/", IsWrapped=true)]
public partial class GetStatementRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
    public SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatementRequest", Namespace="http://FileLocalSCS/", Order=0)]
    public filelocalscs.GetStatementRequestDetail GetStatementRequest1;
    
    public GetStatementRequest()
    {
    }
    
    public GetStatementRequest(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.GetStatementRequestDetail GetStatementRequest1)
    {
        this.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        this.GetStatementRequest1 = GetStatementRequest1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetStatementResponse", WrapperNamespace="http://FileLocalSCS/", IsWrapped=true)]
public partial class GetStatementResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://FileLocalSCS/", Order=0)]
    public filelocalscs.GetStatementResponseDetail GetStatementResult;
    
    public GetStatementResponse()
    {
    }
    
    public GetStatementResponse(filelocalscs.GetStatementResponseDetail GetStatementResult)
    {
        this.GetStatementResult = GetStatementResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ValidateGBL", WrapperNamespace="http://FileLocalSCS/", IsWrapped=true)]
public partial class ValidateGBLRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
    public SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateGBLRequest", Namespace="http://FileLocalSCS/", Order=0)]
    public filelocalscs.ValidateGBLRequestDetail ValidateGBLRequest1;
    
    public ValidateGBLRequest()
    {
    }
    
    public ValidateGBLRequest(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.ValidateGBLRequestDetail ValidateGBLRequest1)
    {
        this.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        this.ValidateGBLRequest1 = ValidateGBLRequest1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ValidateGBLResponse", WrapperNamespace="http://FileLocalSCS/", IsWrapped=true)]
public partial class ValidateGBLResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://FileLocalSCS/", Order=0)]
    public filelocalscs.ValidateGBLResponseDetail ValidateGBLResult;
    
    public ValidateGBLResponse()
    {
    }
    
    public ValidateGBLResponse(filelocalscs.ValidateGBLResponseDetail ValidateGBLResult)
    {
        this.ValidateGBLResult = ValidateGBLResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ValidateTaxpayerForm", WrapperNamespace="http://FileLocalSCS/", IsWrapped=true)]
public partial class ValidateTaxpayerFormRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
    public SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateTaxpayerFormRequest", Namespace="http://FileLocalSCS/", Order=0)]
    public filelocalscs.ValidateTaxpayerFormRequestDetail ValidateTaxpayerFormRequest1;
    
    public ValidateTaxpayerFormRequest()
    {
    }
    
    public ValidateTaxpayerFormRequest(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.ValidateTaxpayerFormRequestDetail ValidateTaxpayerFormRequest1)
    {
        this.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        this.ValidateTaxpayerFormRequest1 = ValidateTaxpayerFormRequest1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ValidateTaxpayerFormResponse", WrapperNamespace="http://FileLocalSCS/", IsWrapped=true)]
public partial class ValidateTaxpayerFormResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://FileLocalSCS/", Order=0)]
    public filelocalscs.ValidateTaxpayerFormResponseDetail ValidateTaxpayerFormResult;
    
    public ValidateTaxpayerFormResponse()
    {
    }
    
    public ValidateTaxpayerFormResponse(filelocalscs.ValidateTaxpayerFormResponseDetail ValidateTaxpayerFormResult)
    {
        this.ValidateTaxpayerFormResult = ValidateTaxpayerFormResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ValidateTaxpayerAccount2", WrapperNamespace="http://FileLocalSCS/", IsWrapped=true)]
public partial class ValidateTaxpayerAccount2Request
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
    public SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateTaxpayerAccount2Request", Namespace="http://FileLocalSCS/", Order=0)]
    public filelocalscs.ValidateTaxpayerAccount2RequestDetail ValidateTaxpayerAccount2Request1;
    
    public ValidateTaxpayerAccount2Request()
    {
    }
    
    public ValidateTaxpayerAccount2Request(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.ValidateTaxpayerAccount2RequestDetail ValidateTaxpayerAccount2Request1)
    {
        this.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        this.ValidateTaxpayerAccount2Request1 = ValidateTaxpayerAccount2Request1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ValidateTaxpayerAccount2Response", WrapperNamespace="http://FileLocalSCS/", IsWrapped=true)]
public partial class ValidateTaxpayerAccount2Response
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://FileLocalSCS/", Order=0)]
    public filelocalscs.ValidateTaxpayerAccount2ResponseDetail ValidateTaxpayerAccount2Result;
    
    public ValidateTaxpayerAccount2Response()
    {
    }
    
    public ValidateTaxpayerAccount2Response(filelocalscs.ValidateTaxpayerAccount2ResponseDetail ValidateTaxpayerAccount2Result)
    {
        this.ValidateTaxpayerAccount2Result = ValidateTaxpayerAccount2Result;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISCSChannel : ISCS, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SCSClient : System.ServiceModel.ClientBase<ISCS>, ISCS
{
    
    public SCSClient()
    {
    }
    
    public SCSClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SCSClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SCSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SCSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    PrintGBLResponse ISCS.PrintGBL(PrintGBLRequest request)
    {
        return base.Channel.PrintGBL(request);
    }
    
    public filelocalscs.PrintGBLResponseDetail PrintGBL(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.PrintGBLRequestDetail PrintGBLRequest1)
    {
        PrintGBLRequest inValue = new PrintGBLRequest();
        inValue.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        inValue.PrintGBLRequest1 = PrintGBLRequest1;
        PrintGBLResponse retVal = ((ISCS)(this)).PrintGBL(inValue);
        return retVal.PrintGBLResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<PrintGBLResponse> ISCS.PrintGBLAsync(PrintGBLRequest request)
    {
        return base.Channel.PrintGBLAsync(request);
    }
    
    public System.Threading.Tasks.Task<PrintGBLResponse> PrintGBLAsync(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.PrintGBLRequestDetail PrintGBLRequest1)
    {
        PrintGBLRequest inValue = new PrintGBLRequest();
        inValue.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        inValue.PrintGBLRequest1 = PrintGBLRequest1;
        return ((ISCS)(this)).PrintGBLAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CalculateGBLRenewalResponse ISCS.CalculateGBLRenewal(CalculateGBLRenewalRequest request)
    {
        return base.Channel.CalculateGBLRenewal(request);
    }
    
    public filelocalscs.CalculateGBLRenewalResponseDetail CalculateGBLRenewal(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.CalculateGBLRenewalRequestDetail CalculateGBLRenewalRequest1)
    {
        CalculateGBLRenewalRequest inValue = new CalculateGBLRenewalRequest();
        inValue.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        inValue.CalculateGBLRenewalRequest1 = CalculateGBLRenewalRequest1;
        CalculateGBLRenewalResponse retVal = ((ISCS)(this)).CalculateGBLRenewal(inValue);
        return retVal.CalculateGBLRenewalResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CalculateGBLRenewalResponse> ISCS.CalculateGBLRenewalAsync(CalculateGBLRenewalRequest request)
    {
        return base.Channel.CalculateGBLRenewalAsync(request);
    }
    
    public System.Threading.Tasks.Task<CalculateGBLRenewalResponse> CalculateGBLRenewalAsync(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.CalculateGBLRenewalRequestDetail CalculateGBLRenewalRequest1)
    {
        CalculateGBLRenewalRequest inValue = new CalculateGBLRenewalRequest();
        inValue.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        inValue.CalculateGBLRenewalRequest1 = CalculateGBLRenewalRequest1;
        return ((ISCS)(this)).CalculateGBLRenewalAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    PaymentRejectionReportResponse ISCS.PaymentRejectionReport(PaymentRejectionReportRequest request)
    {
        return base.Channel.PaymentRejectionReport(request);
    }
    
    public filelocalscs.PaymentRejectionReportResponseDetail PaymentRejectionReport(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.PaymentRejectionReportRequestDetail PaymentRejectionReportRequest1)
    {
        PaymentRejectionReportRequest inValue = new PaymentRejectionReportRequest();
        inValue.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        inValue.PaymentRejectionReportRequest1 = PaymentRejectionReportRequest1;
        PaymentRejectionReportResponse retVal = ((ISCS)(this)).PaymentRejectionReport(inValue);
        return retVal.PaymentRejectionReportResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<PaymentRejectionReportResponse> ISCS.PaymentRejectionReportAsync(PaymentRejectionReportRequest request)
    {
        return base.Channel.PaymentRejectionReportAsync(request);
    }
    
    public System.Threading.Tasks.Task<PaymentRejectionReportResponse> PaymentRejectionReportAsync(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.PaymentRejectionReportRequestDetail PaymentRejectionReportRequest1)
    {
        PaymentRejectionReportRequest inValue = new PaymentRejectionReportRequest();
        inValue.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        inValue.PaymentRejectionReportRequest1 = PaymentRejectionReportRequest1;
        return ((ISCS)(this)).PaymentRejectionReportAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetStatementResponse ISCS.GetStatement(GetStatementRequest request)
    {
        return base.Channel.GetStatement(request);
    }
    
    public filelocalscs.GetStatementResponseDetail GetStatement(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.GetStatementRequestDetail GetStatementRequest1)
    {
        GetStatementRequest inValue = new GetStatementRequest();
        inValue.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        inValue.GetStatementRequest1 = GetStatementRequest1;
        GetStatementResponse retVal = ((ISCS)(this)).GetStatement(inValue);
        return retVal.GetStatementResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetStatementResponse> ISCS.GetStatementAsync(GetStatementRequest request)
    {
        return base.Channel.GetStatementAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetStatementResponse> GetStatementAsync(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.GetStatementRequestDetail GetStatementRequest1)
    {
        GetStatementRequest inValue = new GetStatementRequest();
        inValue.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        inValue.GetStatementRequest1 = GetStatementRequest1;
        return ((ISCS)(this)).GetStatementAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ValidateGBLResponse ISCS.ValidateGBL(ValidateGBLRequest request)
    {
        return base.Channel.ValidateGBL(request);
    }
    
    public filelocalscs.ValidateGBLResponseDetail ValidateGBL(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.ValidateGBLRequestDetail ValidateGBLRequest1)
    {
        ValidateGBLRequest inValue = new ValidateGBLRequest();
        inValue.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        inValue.ValidateGBLRequest1 = ValidateGBLRequest1;
        ValidateGBLResponse retVal = ((ISCS)(this)).ValidateGBL(inValue);
        return retVal.ValidateGBLResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ValidateGBLResponse> ISCS.ValidateGBLAsync(ValidateGBLRequest request)
    {
        return base.Channel.ValidateGBLAsync(request);
    }
    
    public System.Threading.Tasks.Task<ValidateGBLResponse> ValidateGBLAsync(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.ValidateGBLRequestDetail ValidateGBLRequest1)
    {
        ValidateGBLRequest inValue = new ValidateGBLRequest();
        inValue.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        inValue.ValidateGBLRequest1 = ValidateGBLRequest1;
        return ((ISCS)(this)).ValidateGBLAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ValidateTaxpayerFormResponse ISCS.ValidateTaxpayerForm(ValidateTaxpayerFormRequest request)
    {
        return base.Channel.ValidateTaxpayerForm(request);
    }
    
    public filelocalscs.ValidateTaxpayerFormResponseDetail ValidateTaxpayerForm(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.ValidateTaxpayerFormRequestDetail ValidateTaxpayerFormRequest1)
    {
        ValidateTaxpayerFormRequest inValue = new ValidateTaxpayerFormRequest();
        inValue.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        inValue.ValidateTaxpayerFormRequest1 = ValidateTaxpayerFormRequest1;
        ValidateTaxpayerFormResponse retVal = ((ISCS)(this)).ValidateTaxpayerForm(inValue);
        return retVal.ValidateTaxpayerFormResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ValidateTaxpayerFormResponse> ISCS.ValidateTaxpayerFormAsync(ValidateTaxpayerFormRequest request)
    {
        return base.Channel.ValidateTaxpayerFormAsync(request);
    }
    
    public System.Threading.Tasks.Task<ValidateTaxpayerFormResponse> ValidateTaxpayerFormAsync(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.ValidateTaxpayerFormRequestDetail ValidateTaxpayerFormRequest1)
    {
        ValidateTaxpayerFormRequest inValue = new ValidateTaxpayerFormRequest();
        inValue.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        inValue.ValidateTaxpayerFormRequest1 = ValidateTaxpayerFormRequest1;
        return ((ISCS)(this)).ValidateTaxpayerFormAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ValidateTaxpayerAccount2Response ISCS.ValidateTaxpayerAccount2(ValidateTaxpayerAccount2Request request)
    {
        return base.Channel.ValidateTaxpayerAccount2(request);
    }
    
    public filelocalscs.ValidateTaxpayerAccount2ResponseDetail ValidateTaxpayerAccount2(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.ValidateTaxpayerAccount2RequestDetail ValidateTaxpayerAccount2Request1)
    {
        ValidateTaxpayerAccount2Request inValue = new ValidateTaxpayerAccount2Request();
        inValue.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        inValue.ValidateTaxpayerAccount2Request1 = ValidateTaxpayerAccount2Request1;
        ValidateTaxpayerAccount2Response retVal = ((ISCS)(this)).ValidateTaxpayerAccount2(inValue);
        return retVal.ValidateTaxpayerAccount2Result;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ValidateTaxpayerAccount2Response> ISCS.ValidateTaxpayerAccount2Async(ValidateTaxpayerAccount2Request request)
    {
        return base.Channel.ValidateTaxpayerAccount2Async(request);
    }
    
    public System.Threading.Tasks.Task<ValidateTaxpayerAccount2Response> ValidateTaxpayerAccount2Async(SCSSoapAuthenticationHeader SCSSoapAuthenticationHeader, filelocalscs.ValidateTaxpayerAccount2RequestDetail ValidateTaxpayerAccount2Request1)
    {
        ValidateTaxpayerAccount2Request inValue = new ValidateTaxpayerAccount2Request();
        inValue.SCSSoapAuthenticationHeader = SCSSoapAuthenticationHeader;
        inValue.ValidateTaxpayerAccount2Request1 = ValidateTaxpayerAccount2Request1;
        return ((ISCS)(this)).ValidateTaxpayerAccount2Async(inValue);
    }
}
namespace filelocalscs
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrintGBLRequestDetail", Namespace="http://FileLocalSCS/")]
    public partial class PrintGBLRequestDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TaxAccountIDField;
        
        private string UBIField;
        
        private int LicenseYearField;
        
        private string Legal_Business_NameField;
        
        private string Trade_NameField;
        
        private string business_address1Field;
        
        private string business_address2Field;
        
        private string business_cityField;
        
        private string business_stateField;
        
        private string business_zipField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxAccountID
        {
            get
            {
                return this.TaxAccountIDField;
            }
            set
            {
                this.TaxAccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UBI
        {
            get
            {
                return this.UBIField;
            }
            set
            {
                this.UBIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int LicenseYear
        {
            get
            {
                return this.LicenseYearField;
            }
            set
            {
                this.LicenseYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Legal_Business_Name
        {
            get
            {
                return this.Legal_Business_NameField;
            }
            set
            {
                this.Legal_Business_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Trade_Name
        {
            get
            {
                return this.Trade_NameField;
            }
            set
            {
                this.Trade_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string business_address1
        {
            get
            {
                return this.business_address1Field;
            }
            set
            {
                this.business_address1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string business_address2
        {
            get
            {
                return this.business_address2Field;
            }
            set
            {
                this.business_address2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string business_city
        {
            get
            {
                return this.business_cityField;
            }
            set
            {
                this.business_cityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string business_state
        {
            get
            {
                return this.business_stateField;
            }
            set
            {
                this.business_stateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string business_zip
        {
            get
            {
                return this.business_zipField;
            }
            set
            {
                this.business_zipField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrintGBLResponseDetail", Namespace="http://FileLocalSCS/")]
    public partial class PrintGBLResponseDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private SalesTaxOnline.SCS.Data.Code CodeField;
        
        private string DetailField;
        
        private string AdditionalInformationField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SalesTaxOnline.SCS.Data.Code Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detail
        {
            get
            {
                return this.DetailField;
            }
            set
            {
                this.DetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string AdditionalInformation
        {
            get
            {
                return this.AdditionalInformationField;
            }
            set
            {
                this.AdditionalInformationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalculateGBLRenewalRequestDetail", Namespace="http://FileLocalSCS/")]
    public partial class CalculateGBLRenewalRequestDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Xml.XmlElement RequestXmlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement RequestXml
        {
            get
            {
                return this.RequestXmlField;
            }
            set
            {
                this.RequestXmlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalculateGBLRenewalResponseDetail", Namespace="http://FileLocalSCS/")]
    public partial class CalculateGBLRenewalResponseDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Xml.XmlElement ResponseXmlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement ResponseXml
        {
            get
            {
                return this.ResponseXmlField;
            }
            set
            {
                this.ResponseXmlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentRejectionReportRequestDetail", Namespace="http://FileLocalSCS/")]
    public partial class PaymentRejectionReportRequestDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Xml.XmlElement RequestXmlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement RequestXml
        {
            get
            {
                return this.RequestXmlField;
            }
            set
            {
                this.RequestXmlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentRejectionReportResponseDetail", Namespace="http://FileLocalSCS/")]
    public partial class PaymentRejectionReportResponseDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private SalesTaxOnline.SCS.Data.ResponseCode ResponseCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SalesTaxOnline.SCS.Data.ResponseCode ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetStatementRequestDetail", Namespace="http://FileLocalSCS/")]
    public partial class GetStatementRequestDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TaxAccountIDField;
        
        private string UBIField;
        
        private string StateTaxIDField;
        
        private string StatementCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxAccountID
        {
            get
            {
                return this.TaxAccountIDField;
            }
            set
            {
                this.TaxAccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UBI
        {
            get
            {
                return this.UBIField;
            }
            set
            {
                this.UBIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string StateTaxID
        {
            get
            {
                return this.StateTaxIDField;
            }
            set
            {
                this.StateTaxIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string StatementCode
        {
            get
            {
                return this.StatementCodeField;
            }
            set
            {
                this.StatementCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetStatementResponseDetail", Namespace="http://FileLocalSCS/")]
    public partial class GetStatementResponseDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Xml.XmlElement ResponseXmlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement ResponseXml
        {
            get
            {
                return this.ResponseXmlField;
            }
            set
            {
                this.ResponseXmlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateGBLRequestDetail", Namespace="http://FileLocalSCS/")]
    public partial class ValidateGBLRequestDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Xml.XmlElement RequestXmlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement RequestXml
        {
            get
            {
                return this.RequestXmlField;
            }
            set
            {
                this.RequestXmlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateGBLResponseDetail", Namespace="http://FileLocalSCS/")]
    public partial class ValidateGBLResponseDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Xml.XmlElement ResponseXmlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement ResponseXml
        {
            get
            {
                return this.ResponseXmlField;
            }
            set
            {
                this.ResponseXmlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateTaxpayerFormRequestDetail", Namespace="http://FileLocalSCS/")]
    public partial class ValidateTaxpayerFormRequestDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Xml.XmlElement RequestXmlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement RequestXml
        {
            get
            {
                return this.RequestXmlField;
            }
            set
            {
                this.RequestXmlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateTaxpayerFormResponseDetail", Namespace="http://FileLocalSCS/")]
    public partial class ValidateTaxpayerFormResponseDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Xml.XmlElement ResponseXmlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement ResponseXml
        {
            get
            {
                return this.ResponseXmlField;
            }
            set
            {
                this.ResponseXmlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateTaxpayerAccount2RequestDetail", Namespace="http://FileLocalSCS/")]
    public partial class ValidateTaxpayerAccount2RequestDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Xml.XmlElement RequestXmlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement RequestXml
        {
            get
            {
                return this.RequestXmlField;
            }
            set
            {
                this.RequestXmlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateTaxpayerAccount2ResponseDetail", Namespace="http://FileLocalSCS/")]
    public partial class ValidateTaxpayerAccount2ResponseDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private SalesTaxOnline.SCS.Data.Code CodeField;
        
        private string DetailField;
        
        private string AdditionalInformationField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SalesTaxOnline.SCS.Data.Code Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detail
        {
            get
            {
                return this.DetailField;
            }
            set
            {
                this.DetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string AdditionalInformation
        {
            get
            {
                return this.AdditionalInformationField;
            }
            set
            {
                this.AdditionalInformationField = value;
            }
        }
    }
}
namespace SalesTaxOnline.SCS.Data
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Code", Namespace="http://schemas.datacontract.org/2004/07/SalesTaxOnline.SCS.Data")]
    public enum Code : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAIL = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseCode", Namespace="http://schemas.datacontract.org/2004/07/SalesTaxOnline.SCS.Data")]
    public enum ResponseCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
    }
}
namespace filelocalscs.Faults
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StandardFault", Namespace="http://FileLocalSCS/Faults/")]
    public partial class StandardFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ReasonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XmlSchemaValidationFault", Namespace="http://FileLocalSCS/Faults/")]
    public partial class XmlSchemaValidationFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ReasonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }
}
